package com.uber.rocket.entity.notification;

public enum NotificationType {
    DRIVER_RIDE_REQUEST, PASSENGER_RIDE_REQUEST, UPDATE_DRIVER_DATA_REQUEST, UPDATE_DRIVE_PICTURE_REQUEST, RIDE_CANCELED, RIDE_CONFIRMED, RIDE_SCHEDULED
}
