export enum VehicleType {
  LIMOUSINE = 'LIMOUSINE',
  HATCHBACK = 'HATCHBACK',
  CARAVAN = 'CARAVAN',
  COUPE = 'COUPE',
  CONVERTIBLE = 'CONVERTIBLE',
  MINIVAN = 'MINIVAN',
  SUV = 'SUV',
  PICKUP = 'PICKUP',
}
